const TYPES = {
  FETCH_PRODUCTS: 'FETCH_PRODUCTS',
  ADD_PRODUCT: 'ADD_PRODUCT',
  REMOVE_PRODUCT: 'REMOVE_PRODUCT',
  EDIT_PRODUCT: 'EDIT_PRODUCT',
  FETCH_CATEGORIES: 'FETCH_CATEGORIES',
  FETCH_LANGUAGES: 'FETCH_LANGUAGES',
  FETCH_PAYMENT_TYPES: 'FETCH_PAYMENT_TYPES',
  ADD_CART_ITEM: 'ADD_CART_ITEM',
  REMOVE_CART_ITEM: 'REMOVE_CART_ITEM'
};

export default TYPES;
